trigger:
- main

pool:
  name: Default
  demands:
    - agent.name -equals Meshaka77lapLinux

variables:
  pythonVersion: '3.9'  # Ensure this matches your system's Python version

steps:
# Step 1: Ensure Python is Installed and Set Up
- script: |
    sudo apt-get update
    sudo apt-get install -y python3 python3-venv python3-pip
    python3 --version
  displayName: 'Ensure Python is Installed'

# Step 2: Create and Activate Virtual Environment, Install Dependencies
- script: |
    python3 -m venv venv
    source venv/bin/activate
    python -m pip install --upgrade pip
    pip install -r requirements.txt
  displayName: 'Set Up Virtual Environment and Install Dependencies'

# Step 3: Package the Application for Deployment
- script: |
    zip -r app.zip .  # Zip all files in the current directory
  displayName: 'Package Application'

# Step 4: Deploy to Azure Web App
- task: AzureWebApp@1
  inputs:
    azureSubscription: 'newproapp'
    appName: 'newproapp'
    package: $(System.DefaultWorkingDirectory)/app.zip
  displayName: 'Deploy to Azure Web App'
