trigger:
- main

pool:
  name: Default
  demands:
    - agent.name -equals Meshaka77lapLinux

variables:
  pythonVersion: '3.9'  # Ensure this matches your system's Python version

steps:

# Step 1: Ensure Python is Installed and Set Up
- script: |
    echo "Updating package lists and installing Python..."
    sudo apt-get update
    sudo apt-get install -y python3 python3-venv python3-pip
    echo "Python version installed:"
    python3 --version
  displayName: 'Ensure Python is Installed'

# Step 2: Create and Activate Virtual Environment, Install Dependencies
- script: |
    echo "Creating virtual environment..."
    python3 -m venv venv
    echo "Activating virtual environment and installing dependencies..."
    source venv/bin/activate
    python -m pip install --upgrade pip

    if [ ! -f requirements.txt ]; then
      echo "Error: requirements.txt file not found in $(pwd)"
      exit 1
    fi

    pip install -r requirements.txt
  displayName: 'Set Up Virtual Environment and Install Dependencies'

# Step 3: Package the Application for Deployment
- script: |
    echo "Packaging application into app.zip..."
    zip -r app.zip .  # Zip all files in the current directory
  displayName: 'Package Application'

# Step 4: Deploy to Azure Web App
- task: AzureWebApp@1
  inputs:
    azureSubscription: 'newproapp'
    appName: 'newappdish'
    package: $(System.DefaultWorkingDirectory)/app.zip
  displayName: 'Deploy to Azure Web App'
